{% set name = "channels_redis" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/channels_redis-{{ version }}.tar.gz
  sha256: 6bd4f75f4ab4a7db17cee495593ace886d7e914c66f8214a1f247ff6659c073a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - redis-py >=4.5.3
    - msgpack-python >=1.0,<2.dev0
    - asgiref >=3.2.10,<4
    - channels

test:
  imports:
    - channels_redis
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/django/channels_redis/
  summary: Redis-backed ASGI channel layer implementation
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cshaley
    - rxm7706
