{% set name = "channels_redis" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/channels_redis-{{ version }}.tar.gz
  sha256: 740ee7b54f0e28cf2264a940a24453d3f00526a96931f911fcb69228ef245dd2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - redis-py >=4.6
    - msgpack-python >=1.0,<2.dev0
    - asgiref >=3.2.10,<4
    - channels
#    - incremental 24.7.2 requires tomli, which is not installed.
    - tomli

test:
  imports:
    - channels_redis
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: http://github.com/django/channels_redis/
  summary: Redis-backed ASGI channel layer implementation
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cshaley
    - rxm7706
