{% set name = "channels_redis" %}
{% set version = "4.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/channels_redis-{{ version }}.tar.gz
  sha256: 8375e81493e684792efe6e6eca60ef3d7782ef76c6664057d2e5c31e80d636dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - redis-py >=4.6
    - msgpack-python >=1.0,<2.dev0
    - asgiref >=3.2.10,<4
    - channels

test:
  imports:
    - channels_redis
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/django/channels_redis/
  summary: Redis-backed ASGI channel layer implementation
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cshaley
    - rxm7706
